language: php

php:
  - 7.4

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - composer validate --strict
  - vendor/bin/phpcs
  - vendor/bin/phpunit

notifications:
  email: false
  irc: "irc.freenode.org#chesszebra"
